seed: 0
output_dir: ./st_mem/con+rec_v3
exp_name: finetune
resume: null
start_epoch: 0
encoder_path: /home/zehaoqin/ST-MEM/st_mem/new_model/pretrain/mimic/pretrain/encoder.pth
model_name: st_mem_vit_base
mode: finetune
device: cuda

ddp:
  world_size: 1
  rank: -1
  gpu: 3
  dist_url: env://
  dist_backend: nccl
  distributed: True

model:
  seq_len: 2250
  patch_size: 75
  num_leads: 12
  num_classes: 5

dataset:
  filename_col: FILE_NAME
  fs_col: SAMPLE_RATE
  label_col: LABEL
  label_dtype: long
  lead: 12lead
  fs: 250
  # index_dir: /ssd1/stmem/processed_cpsc
  # ecg_dir: /ssd1/stmem/processed_cpsc/ecg
  # ptbxl
  # index_dir: /home/zehaoqin/ST-MEM/dataset/ptbxl/processed
  # ecg_dir: /home/zehaoqin/ST-MEM/dataset/ptbxldata
  # 猝死
  index_dir: /ssd1/qinzehao/cusi/6.10ecg/train
  ecg_dir: /ssd1/qinzehao/cusi/6.10ecg/train

  train_csv: train_index.csv
  valid_csv: val_index.csv
  test_csv: test_index.csv

  rand_augment:
    use: False
    kwargs:
      op_names:
      - shift
      - cutout
      - drop
      - flip
      - erase
      - sine
      - partial_sine
      - partial_white_noise
      level: 10
      num_layers: 2
      prob: 0.5
  train_transforms:
  - random_crop:
      crop_length: 2250
  - highpass_filter:
      fs: 250
      cutoff: 0.67
  - lowpass_filter:
      fs: 250
      cutoff: 40
  - standardize:
      axis: [-1, -2]
  eval_transforms:
  - n_crop:
      crop_length: 2250
      num_segments: 3
  - highpass_filter:
      fs: 250
      cutoff: 0.67
  - lowpass_filter:
      fs: 250
      cutoff: 40
  - standardize:
      axis: [-1, -2]

dataloader:
  batch_size: 128
  num_workers: 8
  pin_memory: True

train:
  epochs: 20
  accum_iter: 1
  warmup_epochs: 0
  min_lr: 0
  blr: 2.0e-4
  lr: null
  weight_decay: 0.05
  dist_eval: false
  max_norm: null
  optimizer: adamw

loss:
# cross_entropy bce
  name: bce

metric:
  # task: multiclass
  task: binary
  compute_on_cpu: true
  sync_on_compute: false
  num_classes: 9
  target_metrics:
  - Accuracy
  - F1Score:
      average: macro
  - AUROC:
      average: macro

test:
  target_metric: loss
# MulticlassAUROC