seed: 0
output_dir: /ssd1/qinzehao/0806
exp_name: pretrain
resume: null
start_epoch: 0
model_name: st_mem_vit_base_dec256d4b
device: cuda
num_device: 4
ddp:
  world_size: 4
  rank: -1
  gpu: 0,1,5,7
  dist_url: env://
  dist_backend: nccl
  distributed: True
# 这里可能对实验结果产生较大影响
model:
  seq_len: 2250
  patch_size: 75
  num_leads: 12
  norm_pix_loss: true

dataset_mimic:
  filename_col: FILE_NAME
  fs_col: SAMPLE_RATE
  lead: 12lead
  fs: 250
  SUBJECT_ID: SUBJECT_ID
  index_dir: /ssd1/stmem/train_data_id
  ecg_dir: /ssd1/stmem/train_data_id/ecg

  train_csv: index.csv

  train_transforms:
  - random_crop:
      crop_length: 2250
  - highpass_filter:
      fs: 250
      cutoff: 0.67
  - lowpass_filter:
      fs: 250
      cutoff: 40
  - standardize:
      axis: [-1, -2]

dataset_code15:
  filename_col: FILE_NAME
  fs_col: SAMPLE_RATE
  lead: 12lead
  fs: 250
  index_dir: /ssd1/stmem/CODE-15
  ecg_dir: /ssd1/stmem/CODE-15

  train_csv: index_data.csv

  train_transforms:
  - random_crop:
      crop_length: 2250
  - highpass_filter:
      fs: 250
      cutoff: 0.67
  - lowpass_filter:
      fs: 250
      cutoff: 40
  - standardize:
      axis: [-1, -2]

dataset_ningbo:
  filename_col: FILE_NAME
  fs_col: SAMPLE_RATE
  lead: 12lead
  fs: 250
  index_dir: /ssd1/stmem/chapman+ningbo
  ecg_dir: /ssd1/stmem/chapman+ningbo/data

  train_csv: index.csv

  train_transforms:
  - random_crop:
      crop_length: 2250
  - highpass_filter:
      fs: 250
      cutoff: 0.67
  - lowpass_filter:
      fs: 250
      cutoff: 40
  - standardize:
      axis: [-1, -2]

dataloader:
  batch_size: 256
  num_workers: 16
  pin_memory: True

train:
  epochs: 100
  accum_iter: 1
  warmup_epochs: 5
  min_lr: 0
  blr: 1.5e-4
  lr: null
  weight_decay: 0.01
  optimizer: adamw
  optimizer_kwargs:
    betas: [0.9, 0.95]
